/**********************************************************************************************************************
 * \file ADC_Queued_Scan.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
*/


#include "ADC.h"
#include "TOM_ISR.h"
#include "MotorMgtSwc.h"
#include "IfxGtm_Tom_Timer.h"
#include <EncoderGpt12.h>
#include "CurrentADC.h"
#include "CommutationControl.h"
#include"Ifxvadc.h"
#include "BackgroundADC.h"
#include "ConfigurationIsr.h"

IfxGtm_Tom_Timer g_tom1_timerDriver;
IfxGtm_Tom_Timer_Config tom1_timerConfig;

#define TOM1_TIMER_FREQ     (20000)

IFX_INTERRUPT(interruptGtmTom1_Timer, 0 , ISR_PRIORITY_TOM1_TIMER);
IFX_INTERRUPT(interruptGtmATom_PhaseV, 0 , ISR_PRIORITY_ATOM_PWM_VPHASE);

void interruptGtmTom1_Timer(void)
{
    Current_updateDuty();
    g_bldc.testcount++;
    if(MOTOR_STATE_RUNNING == g_bldc.state)
    {
       if( g_bldc.loop_mode == LOOP_MODE_CURRENT)
       {
           u8DrvDuty = u8DrvDuty_Current;
       }
    }
    IfxGtm_Tom_Timer_acknowledgeTimerIrq(&g_tom1_timerDriver);
}

void initGtmTom1_Timer(void)
{
    IfxGtm_enable(&MODULE_GTM);
    IfxGtm_Tom_Timer_initConfig(&tom1_timerConfig, &MODULE_GTM);

    tom1_timerConfig.base.isrPriority     = ISR_PRIORITY_TOM1_TIMER;
    tom1_timerConfig.base.isrProvider     = IfxSrc_Tos_cpu0;
    tom1_timerConfig.tom                  = IfxGtm_Tom_2;
    tom1_timerConfig.timerChannel         = IfxGtm_Tom_Ch_1;
    tom1_timerConfig.clock                = IfxGtm_Tom_Ch_ClkSrc_cmuFxclk1;
    tom1_timerConfig.base.frequency       = TOM1_TIMER_FREQ;
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);
    IfxGtm_Tom_Timer_init(&g_tom1_timerDriver, &tom1_timerConfig);
    IfxGtm_Tom_Timer_run(&g_tom1_timerDriver);
}

void interruptGtmATom_PhaseV(void)
{
    //    Current_updateDuty();
    g_bldc.testcount++;
}










