/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include <CurrentADC.h>
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "MotorMgtSwc.h"
#include "ADC.h"
#include "MULTICAN.h"
#include "CommutationPoint.h"
#include "BackgroundADC.h"
#include "TOM_ISR.h"

extern IfxCpu_syncEvent g_cpuSyncEvent;
//uint8 theOld_PosCtrlStep=0;

int core2_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG2 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
//    InitCurrentADC_BCMode();
    initGtmTom_currentADC();


    while(1)
    {
        if(MOTOR_STATE_RUNNING == g_bldc.state||MOTOR_STATE_STARTUP == g_bldc.state)
        {
          if(K_ROT_DIR_CCW == g_bldc.rot_dir)
          {
             g_PosCtrlStep = Commutation_getCommuPosIndex(K_ROT_DIR_CCW);
             g_PosCtrlStep += POS_CTRL_STEP_OFFSET_CCW;
          }
          if(K_ROT_DIR_CW == g_bldc.rot_dir)
          {
              g_PosCtrlStep = Commutation_getCommuPosIndex(K_ROT_DIR_CW);
              g_PosCtrlStep += POS_CTRL_STEP_OFFSET_CW;
          }
          if(g_PosCtrlStep!=theOld_PosCtrlStep)
          {
            theOld_PosCtrlStep = g_PosCtrlStep;
            GtmTomCurrent_6Step(g_PosCtrlStep % 6);
            IfxPort_setPinMode(&MODULE_P32, 2,  IfxPort_Mode_outputPushPullGeneral);
            IfxPort_togglePin(&MODULE_P32, 2);
          }
        }
        else if (MOTOR_STATE_STOP == g_bldc.state)
        {
            g_bldc.CurrentU_BUS = 0;//Avg_current_offset[0]-322;
            g_bldc.CurrentW_BUS = 0;//Avg_current_offset[1]-316;
            g_bldc.CurrentV_BUS = 0;//Avg_current_offset[2]-321;
        }
    }
    return (1);
}
