/*********************************************************************************************************************
 * Copyright (c) 2021, Infineon Technologies AG
 *
 * 
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 * 
 *********************************************************************************************************************/


/********************************************************************************************************
 * @file        TLE926x_SPI.c
 *
 * @brief       Implementation of all SPI related functions
 *
 * @version     V1.0.0
 * @date        
 * @author      Fedy Farhat
 * @author      Michael Schaffarczyk
 ********************************************************************************************************/



/* ================================================================================ */
/* ============================   HEADER FILES     ================================ */
/* ================================================================================ */ 

#include "TLE926x_SPI.h"
#include "cpu.h"
#include "stdint.h"
#include "spi_pal.h"


    uint16_t RxBufffer = 0;

/* ================================================================================ */
/* =======================   SPI communication functions     ====================== */
/* ================================================================================ */ 



uint8_t sbc_spi_init(void) {

	//TO BE IMPLEMENTED
	SPI_MasterInit(&SPI0spi1Instance,&SPI0spi1_MasterConfig0);
	return 0;
}



uint16_t SBC_SPI_TRANSFER16(uint8_t Upper, uint8_t Lower)
{

	//TO BE IMPLEMENTED
	uint16_t Tx_Buf=0;
	uint16_t Rx_Buf=0;
	uint16_t RxBuff_Upper = 0;
	uint16_t RxBuff_Lower = 0;
	Tx_Buf = ((Lower << 8) | Upper);

	SPI_MasterTransferBlocking(&SPI0spi1Instance,&Tx_Buf,&Rx_Buf,1,1000);

/*	RxBuff_Upper = (Rx_Buf >> 8) & 0xFF;
	RxBuff_Lower = Rx_Buf & 0xFF;

	Rx_Buf = (RxBuff_Lower << 8 ) | RxBuff_Upper ;*/

	RxBufffer = Rx_Buf;
	return Rx_Buf;
}
