/********************************************************************************************************************
 * \file MULTICAN_DebugCanMsg.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef MULTICAN_DEBUGCANMSG_H_
#define MULTICAN_DEBUGCANMSG_H_ 1

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <stdio.h>
#include <string.h>
#include "Ifx_Types.h"
#include "IfxMultican_Can.h"
#include "IfxMultican.h"
#include "IfxPort.h"                                            /* For GPIO Port Pin Control                         */



/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define CAN_MESSAGE_RXD_ID01        0x888
#define CAN_MESSAGE_RXD_ID02        0x999
#define CAN_MESSAGE_RXD_ID03        0x988
#define CAN_MESSAGE_RXD_ID04        0x977

#define CAN_MESSAGE_TXD_ID00        0x776                       /* Message ID that will be used in arbitration phase */
#define CAN_MESSAGE_TXD_ID01        0x777                       /* Message ID that will be used in arbitration phase */
#define CAN_MESSAGE_TXD_ID02        0x778
#define CAN_MESSAGE_TXD_ID03        0x779
#define CAN_MESSAGE_TXD_ID04        0x780
#define CAN_MESSAGE_TXD_ID05        0x781
#define CAN_MESSAGE_TXD_ID06        0x782
#define CAN_MESSAGE_TXD_ID07        0x783

#define CAN_MOT_CMD_STOP                (0x00)
#define CAN_MOT_CMD_OPENLOOP_START      (0x01)
#define CAN_MOT_CMD_FOC_START           (0x02)
#define CAN_MOT_CMD_FOC_DOUBLE_LOOP     (0x03)

#define CAN_MOT_CMD_START_VECTORFIXED   (0x09)
#define CAN_MOT_CMD_ELEANGL_UPDATE   (0x08)

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
extern IfxMultican_Status  debug_sendStatus;
extern IfxMultican_Status  NormalMsg_sendStatus;

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/
extern void DebugCanMsg_IsrRxHandler(void);
extern void DebugCanMsg_transmitCurrentMsg(void);
extern void DebugCanMsg_transimitNormalMsg(void);

#endif /* MULTICAN_DEBUGCANMSG_H_ */
