/**********************************************************************************************************************
 * \file Flash_Programming.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <DataFlash_ZeroOffest.h>
#include <string.h>
#include "Ifx_Types.h"
#include "IfxFlash.h"
#include "IfxCpu.h"
#include "MotorMgtSwc.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define DFLASH_PAGE_LENGTH          IFXFLASH_DFLASH_PAGE_LENGTH /* 0x8 = 8 Bytes (smallest unit that can be
                                                                 * programmed in the Data Flash memory (DFLASH))    */
#define FLASH_MODULE                0                           /* Macro to select the flash (PMU) module           */
#define DATA_FLASH_0                IfxFlash_FlashType_D0       /* Define the Data Flash Bank to be used            */


#define Step_Offset_CW_Write             (g_calibration.Step_offset_CW)
#define Step_Offset_CCW_Write            (g_calibration.Step_offset_CCW)
#define Zero_Offset_CW_Write             (g_calibration.Zero_offset_CW)
#define Zero_Offset_CCW_Write            (g_calibration.Zero_offset_CCW)

#define MotorType_Write                  (g_calibration.MotorType)

#define SPEED_KP                         (g_calibration.Speed_KP)
#define SPEED_KI                         (g_calibration.Speed_KI)
#define SPEED_KD                         (g_calibration.Speed_KD)

#define CURRENT_KP                         (g_calibration.Current_KP)
#define CURRENT_KI                         (g_calibration.Current_KI)

#define DFLASH_STARTING_ADDRESS_OFFSET        0xAF000000                  /* Address of the DFLASH where the data is written  */
#define DFLASH_STARTING_ADDRESS_MPTORTYPE     0xAF002000//8KB
#define DFLASH_STARTING_ADDRESS_SPEEDPI       0xAF004000
#define DFLASH_STARTING_ADDRESS_CURRENTPI     0xAF006000

#define DFLASH_SECTORS_CLAERNUM        1                         /* Number of DFLASH sectors to be erased   1         */

#define MEM(address)                *((uint32 *)(address))      /* Macro to simplify the access to a memory address */

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* This function flashes the Data Flash memory.
 * It is not needed to run this function from the PSPR, thus it can call functions from the Program Flash memory.
 */
#define  page_Offeset_0      (0)  //0                                             /* Variable to cycle over all the pages             */
#define  page_Offeset_1      (1)  //1

uint8 Step_Offset_CW_Writing;
uint8 Step_Offset_CCW_Writing;
uint8 Zero_Offset_CW_Writing;
uint8 Zero_Offset_CCW_Writing;

void write_Offset_DataFlash()
{

    /* --------------- ERASE PROCESS --------------- */
    /* Get the current password of the Safety WatchDog module */
    uint16 endInitSafetyPassword = IfxScuWdt_getSafetyWatchdogPassword();

    /* Erase the sector */
    IfxScuWdt_clearSafetyEndinit(endInitSafetyPassword);        /* Disable EndInit protection                       */
    IfxFlash_eraseMultipleSectors(DFLASH_STARTING_ADDRESS_OFFSET, DFLASH_SECTORS_CLAERNUM); /* Erase the given sector           */
    IfxScuWdt_setSafetyEndinit(endInitSafetyPassword);          /* Enable EndInit protection                        */

    /* Wait until the sector is erased */
    IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);

    /* --------------- WRITE PROCESS --------------- */
    {
        uint32 pageAddr = DFLASH_STARTING_ADDRESS_OFFSET + (page_Offeset_0 * DFLASH_PAGE_LENGTH); /* Get the address of the page     */

        /* Enter in page mode */
        IfxFlash_enterPageMode(pageAddr);

        /* Wait until page mode is entered */
        IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);

        /* Load data to be written in the page */
        IfxFlash_loadPage2X32(pageAddr, Step_Offset_CW_Write, Step_Offset_CCW_Write); /* Load two words of 32 bits each            */

        /* Write the loaded page */
        IfxScuWdt_clearSafetyEndinit(endInitSafetyPassword);    /* Disable EndInit protection                       */
        IfxFlash_writePage(pageAddr);                           /* Write the page                                   */
        IfxScuWdt_setSafetyEndinit(endInitSafetyPassword);      /* Enable EndInit protection                        */

        /* Wait until the data is written in the Data Flash memory */
        IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);
    }

    {
        uint32 pageAddr = DFLASH_STARTING_ADDRESS_OFFSET + (page_Offeset_1 * DFLASH_PAGE_LENGTH); /* Get the address of the page     */

        /* Enter in page mode */
        IfxFlash_enterPageMode(pageAddr);

        /* Wait until page mode is entered */
        IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);

        /* Load data to be written in the page */
        IfxFlash_loadPage2X32(pageAddr, Zero_Offset_CW_Write, Zero_Offset_CCW_Write); /* Load two words of 32 bits each            */

        /* Write the loaded page */
        IfxScuWdt_clearSafetyEndinit(endInitSafetyPassword);    /* Disable EndInit protection                       */
        IfxFlash_writePage(pageAddr);                           /* Write the page                                   */
        IfxScuWdt_setSafetyEndinit(endInitSafetyPassword);      /* Enable EndInit protection                        */

        /* Wait until the data is written in the Data Flash memory */
        IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);
    }
}

void write_Type_DataFlash()
{

    uint16 endInitSafetyPassword = IfxScuWdt_getSafetyWatchdogPassword();

     /* Erase the sector */
     IfxScuWdt_clearSafetyEndinit(endInitSafetyPassword);        /* Disable EndInit protection                       */
     IfxFlash_eraseMultipleSectors(DFLASH_STARTING_ADDRESS_MPTORTYPE, DFLASH_SECTORS_CLAERNUM); /* Erase the given sector  DFLASH_NUM_SECTORS         */
     IfxScuWdt_setSafetyEndinit(endInitSafetyPassword);          /* Enable EndInit protection                        */

     /* Wait until the sector is erased */
     IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);

      uint32 pageAddr = DFLASH_STARTING_ADDRESS_MPTORTYPE + (page_Offeset_0 * DFLASH_PAGE_LENGTH); /* Get the address of the page     */


     /* Enter in page mode */
     IfxFlash_enterPageMode(pageAddr);

     /* Wait until page mode is entered */
     IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);

     /* Load data to be written in the page */
     IfxFlash_loadPage2X32(pageAddr, MotorType_Write,0); /* Load two words of 32 bits each            */

     /* Write the loaded page */
     IfxScuWdt_clearSafetyEndinit(endInitSafetyPassword);    /* Disable EndInit protection                       */
     IfxFlash_writePage(pageAddr);                           /* Write the page                                   */
     IfxScuWdt_setSafetyEndinit(endInitSafetyPassword);      /* Enable EndInit protection                        */

     /* Wait until the data is written in the Data Flash memory */
     IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);
}

void write_SPEEDPI_DataFlash(void)
{

    uint16 endInitSafetyPassword = IfxScuWdt_getSafetyWatchdogPassword();

     /* Erase the sector */
     IfxScuWdt_clearSafetyEndinit(endInitSafetyPassword);        /* Disable EndInit protection                       */
     IfxFlash_eraseMultipleSectors(DFLASH_STARTING_ADDRESS_SPEEDPI, DFLASH_SECTORS_CLAERNUM); /* Erase the given sector  DFLASH_NUM_SECTORS         */
     IfxScuWdt_setSafetyEndinit(endInitSafetyPassword);          /* Enable EndInit protection                        */

     /* Wait until the sector is erased */
     IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);

     {
          uint32 pageAddr = DFLASH_STARTING_ADDRESS_SPEEDPI + (page_Offeset_0 * DFLASH_PAGE_LENGTH); /* Get the address of the page     */


         /* Enter in page mode */
         IfxFlash_enterPageMode(pageAddr);

         /* Wait until page mode is entered */
         IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);

         /* Load data to be written in the page */
         IfxFlash_loadPage2X32(pageAddr, SPEED_KP,SPEED_KI); /* Load two words of 32 bits each            */

         /* Write the loaded page */
         IfxScuWdt_clearSafetyEndinit(endInitSafetyPassword);    /* Disable EndInit protection                       */
         IfxFlash_writePage(pageAddr);                           /* Write the page                                   */
         IfxScuWdt_setSafetyEndinit(endInitSafetyPassword);      /* Enable EndInit protection                        */

         /* Wait until the data is written in the Data Flash memory */
         IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);
     }

     {
         uint32 pageAddr = DFLASH_STARTING_ADDRESS_SPEEDPI + (page_Offeset_1 * DFLASH_PAGE_LENGTH); /* Get the address of the page     */

         /* Enter in page mode */
         IfxFlash_enterPageMode(pageAddr);

         /* Wait until page mode is entered */
         IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);

         /* Load data to be written in the page */
         IfxFlash_loadPage2X32(pageAddr, SPEED_KD, 0); /* Load two words of 32 bits each            */

         /* Write the loaded page */
         IfxScuWdt_clearSafetyEndinit(endInitSafetyPassword);    /* Disable EndInit protection                       */
         IfxFlash_writePage(pageAddr);                           /* Write the page                                   */
         IfxScuWdt_setSafetyEndinit(endInitSafetyPassword);      /* Enable EndInit protection                        */

         /* Wait until the data is written in the Data Flash memory */
         IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);
     }


}

void write_CURRENTPI_DataFlash(void)
{

    uint16 endInitSafetyPassword = IfxScuWdt_getSafetyWatchdogPassword();

     /* Erase the sector */
     IfxScuWdt_clearSafetyEndinit(endInitSafetyPassword);        /* Disable EndInit protection                       */
     IfxFlash_eraseMultipleSectors(DFLASH_STARTING_ADDRESS_CURRENTPI, DFLASH_SECTORS_CLAERNUM); /* Erase the given sector  DFLASH_NUM_SECTORS         */
     IfxScuWdt_setSafetyEndinit(endInitSafetyPassword);          /* Enable EndInit protection                        */

     /* Wait until the sector is erased */
     IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);

      uint32 pageAddr = DFLASH_STARTING_ADDRESS_CURRENTPI + (page_Offeset_0 * DFLASH_PAGE_LENGTH); /* Get the address of the page     */


     /* Enter in page mode */
     IfxFlash_enterPageMode(pageAddr);

     /* Wait until page mode is entered */
     IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);

     /* Load data to be written in the page */
     IfxFlash_loadPage2X32(pageAddr, CURRENT_KP,CURRENT_KI); /* Load two words of 32 bits each            */

     /* Write the loaded page */
     IfxScuWdt_clearSafetyEndinit(endInitSafetyPassword);    /* Disable EndInit protection                       */
     IfxFlash_writePage(pageAddr);                           /* Write the page                                   */
     IfxScuWdt_setSafetyEndinit(endInitSafetyPassword);      /* Enable EndInit protection                        */

     /* Wait until the data is written in the Data Flash memory */
     IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);
}

uint32 Step_Offset_CW_Read;
uint32 Step_Offset_CCW_Read;
uint32 Zero_Offset_CW_Read;
uint32 Zero_Offset_CCW_Read;

uint32 MotorTybe_Read;

uint32 SpeedKP_Read;
uint32 SpeedKI_Read;
uint32 SpeedKD_Read;
uint32 CurrentKP_Read;
uint32 CurrentKI_Read;

/* This function verifies if the data has been correctly written in the Data Flash */
void ReadDataFlash_Calibration(void)
{

    uint32 Addr_offset = 4;                                         /* Variable to cycle over all the words in a page   */

    uint32 pageAddr_Step_Offset = DFLASH_STARTING_ADDRESS_OFFSET + (page_Offeset_0 * DFLASH_PAGE_LENGTH);    /* Get the address of the page  */
    uint32 pageAddr_Zero_Offset = DFLASH_STARTING_ADDRESS_OFFSET + (page_Offeset_1 * DFLASH_PAGE_LENGTH);
    uint32 pageAddr_MotorType   = DFLASH_STARTING_ADDRESS_MPTORTYPE + (page_Offeset_0 * DFLASH_PAGE_LENGTH);

    uint32 pageAddr_SpeedKPI   = DFLASH_STARTING_ADDRESS_SPEEDPI + (page_Offeset_0 * DFLASH_PAGE_LENGTH);
    uint32 pageAddr_SpeedKD    = DFLASH_STARTING_ADDRESS_SPEEDPI + (page_Offeset_1 * DFLASH_PAGE_LENGTH);

    uint32 pageAddr_CurrentKPI   = DFLASH_STARTING_ADDRESS_CURRENTPI + (page_Offeset_0 * DFLASH_PAGE_LENGTH);

    Step_Offset_CW_Read = MEM(pageAddr_Step_Offset);//L
    Step_Offset_CCW_Read = MEM(pageAddr_Step_Offset + Addr_offset);//H

    Zero_Offset_CW_Read  = MEM(pageAddr_Zero_Offset);
    Zero_Offset_CCW_Read = MEM(pageAddr_Zero_Offset + Addr_offset);

    MotorTybe_Read = MEM(pageAddr_MotorType);

    SpeedKP_Read = MEM(pageAddr_SpeedKPI);
    SpeedKI_Read = MEM(pageAddr_SpeedKPI+Addr_offset);
    SpeedKD_Read = MEM(pageAddr_SpeedKD);

    CurrentKP_Read = MEM(pageAddr_CurrentKPI);
    CurrentKI_Read = MEM(pageAddr_CurrentKPI+Addr_offset);
}

void DataFlashOffset_Writing(void)
{
   static uint8 Write_Offset_Enabel = 0;
   Write_Offset_Enabel = g_calibration.Offset_Write_Enable;

   if(Write_Offset_Enabel)
   {
      write_Offset_DataFlash();
   }
}

void DataFlashType_Writing(void)
{
    static uint8 Write_Tybe_Enabel = 0;
    Write_Tybe_Enabel = g_calibration.Type_Write_Enable;
    if(Write_Tybe_Enabel)
    {
       write_Type_DataFlash();
    }
}

void DataFlashSpeedPI_Writing(void)
{
    static uint8 Write_SpeedPI_Enabel = 0;
    Write_SpeedPI_Enabel = g_calibration.Speed_KPI_Write_Enabel;
    if(Write_SpeedPI_Enabel)
    {
        write_SPEEDPI_DataFlash();
    }
}

void DataFlashCurrentPI_Writing(void)
{
    static uint8 Write_CurrentPI_Enabel = 0;
    Write_CurrentPI_Enabel = g_calibration.Current_KPI_Write_Enabel;
    if(Write_CurrentPI_Enabel)
    {
        write_CURRENTPI_DataFlash();
    }
}


void DataFlash_CalibrationInit(void)
{
    DataFlashOffset_Writing();
    DataFlashType_Writing();
    DataFlashSpeedPI_Writing();
    DataFlashCurrentPI_Writing();

    ReadDataFlash_Calibration();

}
