/**********************************************************************************************************************
 * \file Flash_Programming.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef DATAFLASH_ZEROOFFSET_H_
#define DATAFLASH_ZEROOFFSET_H_

#include "platform_types.h"
#include "Compilers.h"
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

void write_Offset_DataFlash(void);      /* Function that flashes the Data Flash memory                                      */
void write_Type_DataFlash(void);
void write_CURRENTPI_DataFlash(void);
void write_SPEEDPI_DataFlash(void);

void ReadDataFlash_Calibration(void);     /* Function that verifies the data written in the Data Flash memory          */

void DataFlashOffset_Writing(void);
void DataFlashType_Writing(void);
void DataFlashSpeedPI_Writing(void);
void DataFlashCurrentPI_Writing(void);

void DataFlash_CalibrationInit(void);

IFX_EXTERN  uint32 Step_Offset_CW_Read;
IFX_EXTERN  uint32 Step_Offset_CCW_Read;
IFX_EXTERN  uint32 Zero_Offset_CW_Read;
IFX_EXTERN  uint32 Zero_Offset_CCW_Read;
IFX_EXTERN  uint32 MotorTybe_Read;
IFX_EXTERN  uint32 SpeedKP_Read;
IFX_EXTERN  uint32 SpeedKI_Read;
IFX_EXTERN  uint32 SpeedKD_Read;
IFX_EXTERN  uint32 CurrentKP_Read;
IFX_EXTERN  uint32 CurrentKI_Read;
#endif /* DATAFLASH_ZEROOFFSET_H_ */
