/**********************************************************************************************************************
 * \file ADC_Queued_Scan.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef ADC_H_
#define ADC_H_

#include "Vadc/Adc/IfxVadc_Adc.h"
#include "_Reg/IfxVadc_reg.h"
#include "Cpu/Std/Platform_Types.h"


IFX_EXTERN uint16 ADC_result[6][8];
IFX_EXTERN IfxVadc_Adc_Group adcGroup[6];
IFX_EXTERN IfxVadc_Adc_Channel adcChannel[6][8];


#define TEMP_Group                  (3)      /*The group ID of temperature ADC*/
#define TEMP_Channel                (5)      /*The channel ID of temperature ADC*/


#define VlotageBUS_Group            (3)      /*The group ID of VlotageBUS ADC*/
#define VlotageBUS_Channel         (2)      /*The channel ID of VlotageBUS ADC*/

#define Factor_DAC                  (5.0/4096.0)
#define Factor_phase_Vpower         (215.0/15.0)

void ADC_init(void);
void CurrentADC_init(void);
void SingleADC_Init(uint8 chnIx,uint8 group_i);

void RegisterFiltering(void);

void ADC_Scan(void);
void CurrentScan(void);
void Multi_ADC_init(void);
void Temp_Voltage_DetectScan(void);

void DAC_Scan(void);

void Current_filtering(void);
void initGtmTom_currentADC(void);

#endif /* ADC_H_ */
