/**********************************************************************************************************************
 * \file ADC_Queued_Scan.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef CURRENT_ADC_H_
#define CURRENT_ADC_H_

#include "Vadc/Adc/IfxVadc_Adc.h"
#include "_Reg/IfxVadc_reg.h"
#include "Cpu/Std/Platform_Types.h"
#include <GTM_ATOM_PWM_6Step.h>
#include "CommutationControl.h"
#include "Bsp.h"
#include "IfxPort.h"

extern uint16 ADC_result[6][8];

extern float32 Avg_current_offset[3];

void interruptGtmTom_currentADC(void);
void initGtmTom_currentADC(void);

void initGtmTom_currentADC_Freq(void);
void CurrentOffsetDetect(void);

void initSTM(void);

void PhaseCurrent_Calculate(int nchannel);

void GtmTomCurrent_6Step(enComutateDriverIndex step);


#endif /* CURRENT_ADC_H_ */
