/********************************************************************************************************************
 * \file MULTICAN.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <EncoderGpt12.h>
#include <TempDetect.h>
#include "MULTICAN.h"
#include "IfxCpu_Intrinsics.h"
#include "IfxGpt12_reg.h"
#include "AppTorqueControl.h"
#include "Configuration.h"
#include "ConfigurationISR.h"
#include "MotorMgtSwc.h"
#include "ADC.h"
#include "spi_encoder.h"
#include "velocityPI.h"
#include <DataFlash_ZeroOffest.h>

#if(0)
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
 AppMulticanType   g_candebug;                               /* Global MULTICAN configuration and control structure   */
 //  extern qspiComm g_qspi;
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* Macro to define Interrupt Service Routine.
 * This macro:
 * - defines linker section as .intvec_tc<vector number>_<interrupt priority>.
 * - defines compiler specific attribute for the interrupt functions.
 * - defines the Interrupt service routine as ISR function.
 *
 * IFX_INTERRUPT(isr, vectabNum, priority)
 *  - isr: Name of the ISR function.
 *  - vectabNum: Vector table number.
 *  - priority: Interrupt priority. Refer Usage of Interrupt Macro for more details.
 */
IFX_INTERRUPT(DebugcanIsrTxHandler, 0, ISR_PRIORITY_CAN_debug_TX);
IFX_INTERRUPT(DebugcanIsrRxHandler, 0, ISR_PRIORITY_CAN_debug_RX);

/* Interrupt Service Routine (ISR) called once the TX interrupt has been generated.
 * Turns on the LED1 to indicate successful CAN message transmission.
 */



void DebugcanIsrTxHandler(void)
{
    /* Just to indicate that the CAN message has been transmitted by turning on LED1 */
    //IfxPort_setPinLow(g_led.led1.port, g_led.led1.pinIndex);

    Ifx__NOP(1);
}

/* Interrupt Service Routine (ISR) called once the RX interrupt has been generated.
 * Compares the content of the received CAN message with the content of the transmitted CAN message
 * and in case of success, turns on the LED2 to indicate successful CAN message reception.
 */
uint32 can_rx_id;
uint8  rx_seq = 0;
uint8 test_data_invalid = 9;
void DebugcanIsrRxHandler(void)
{
    IfxMultican_Status readStatus;
    /* Read the received CAN message and store the status of the operation */

#if(CAN_PINMAP_MDA48VBLDC_CAN0==1)

    readStatus = IfxMultican_Can_MsgObj_readMessage(&g_candebug.canSrcMsgObjRx, &g_candebug.rxSrcMsg);

    if( g_candebug.rxSrcMsg.id  == CAN_MESSAGE_RXD_ID01)
    {
          g_bldc.cmd         = (enMotorCmd)(g_candebug.rxSrcMsg.data[0]);
          g_bldc.RefTorque = (uint8)(g_candebug.rxSrcMsg.data[0]>>8);
          g_bldc.Refspeed    = (uint16)(g_candebug.rxSrcMsg.data[0]>>16);
          g_bldc.loop_cmd = (MotorLoopCmd)(g_candebug.rxSrcMsg.data[1]);
          g_bldc.RefPosition = (uint16)(g_candebug.rxSrcMsg.data[1]>>16);
    }

    if( g_candebug.rxSrcMsg.id  == CAN_MESSAGE_RXD_ID02)
      {
            g_bldc.Step_offset_CW  = (uint8)(g_candebug.rxSrcMsg.data[0]);
            g_bldc.Step_offset_CCW = (uint8)(g_candebug.rxSrcMsg.data[0]>>8);
            g_bldc.Zero_offset_CW  = (uint8)(g_candebug.rxSrcMsg.data[0]>>16);
            g_bldc.Zero_offset_CCW = (uint8)(g_candebug.rxSrcMsg.data[0]>>24);
            g_bldc.Offset_Write_Enable = (uint8)(g_candebug.rxSrcMsg.data[1]);
      }


#endif

#if(CAN_PINMAP_TC275LITE_KIT_CAN==1)
    readStatus = IfxMultican_Can_MsgObj_readMessage(&g_candebug.canDstMsgObjRx, &g_candebug.rxDstMsg);

    if(g_candebug.rxDstMsg.id==CAN_MESSAGE_RXD_ID01)
    {
          g_bldc.cmd=(uint8)(g_candebug.rxDstMsg.data[0]);
          g_bldc.duty=(uint8)(g_candebug.rxDstMsg.data[0]>>8);
    }
#endif

}

/* Function to initialize MULTICAN module, nodes and message objects related for this application use case */

void initMulticanDebug(void)
{

    /* ==========================================================================================
     * CAN module configuration and initialization:
     * ==========================================================================================
     *  - load default CAN module configuration into configuration structure
     *
     *  - define the interrupt priority for both interrupt node pointers used in the example
     *
     *  - initialize CAN module with the modified configuration
     * ==========================================================================================
     */
    IfxMultican_Can_initModuleConfig(&g_candebug.canConfig, &MODULE_CAN);

    g_candebug.canConfig.nodePointer[TX_INTERRUPT_SRC_ID].priority = ISR_PRIORITY_CAN_debug_TX;
    g_candebug.canConfig.nodePointer[RX_INTERRUPT_SRC_ID].priority = ISR_PRIORITY_CAN_debug_RX;

    IfxMultican_Can_initModule(&g_candebug.can, &g_candebug.canConfig);

#if(CAN_PINMAP_MDA48VBLDC_CAN0==1)
    {
        /* ==========================================================================================
         * Source CAN node configuration and initialization:
         * ==========================================================================================
         *  - load default CAN node configuration into configuration structure
         *
         *  - set source CAN node in the "Loop-Back" mode (no external pins will be used)
         *  - assign source CAN node to CAN node 0
         *
         *  - initialize the source CAN node with the modified configuration
         * ==========================================================================================
         */
        IfxMultican_Can_Node_initConfig(&g_candebug.canNodeConfig, &g_candebug.can);

#if(CAN_LOOPBACK_MODE)
         g_candebug.canNodeConfig.loopBackMode = TRUE;
#endif

          g_candebug.canNodeConfig.nodeId = IfxMultican_NodeId_0;
          g_candebug.canNodeConfig.rxPin  = &IfxMultican_RXD0A_P02_1_IN;
          g_candebug.canNodeConfig.txPin  = &IfxMultican_TXD0_P02_0_OUT;
          g_candebug.canNodeConfig.baudrate = 500000;
        IfxMultican_Can_Node_init(&g_candebug.canSrcNode, &g_candebug.canNodeConfig);

        /* ==========================================================================================
         * Source message object configuration and initialization:
         * ==========================================================================================
         *  - load default CAN message object configuration into configuration structure
         *
         *  - define the message object ID
         *  - define the CAN message ID used during arbitration phase
         *  - define the message object as a transmit message object
         *  - enable interrupt generation in case of CAN message transmission
         *  - define interrupt node pointer to be used
         *
         *  - initialize the source CAN message object with the modified configuration
         * ==========================================================================================
         */
        IfxMultican_Can_MsgObj_initConfig(&g_candebug.canMsgObjConfig, &g_candebug.canSrcNode);

        g_candebug.canMsgObjConfig.msgObjId = SRC_MESSAGE_OBJECT_TX_ID;
        g_candebug.canMsgObjConfig.messageId = CAN_MESSAGE_TXD_ID01;
        g_candebug.canMsgObjConfig.frame = IfxMultican_Frame_transmit;
        g_candebug.canMsgObjConfig.txInterrupt.enabled = FALSE;
        g_candebug.canMsgObjConfig.control.extendedFrame = TRUE;
        g_candebug.canMsgObjConfig.txInterrupt.srcId = TX_INTERRUPT_SRC_ID;

        IfxMultican_Can_MsgObj_init(&g_candebug.canSrcMsgObjTx, &g_candebug.canMsgObjConfig);

        /* ==========================================================================================
         * Rx message object configuration and initialization:
         * ==========================================================================================
         *  - load default CAN message object configuration into configuration structure
         *
         *  - define the message object ID (different than the ID used for source MO)
         *  - define the CAN message ID used during arbitration phase (same as ID used for source MO)
         *  - define the message object as a receive message object
         *  - enable interrupt generation in case of CAN message transmission
         *  - define interrupt node pointer to be used (different than the one used for source MO)
         *
         *  - initialize the destination CAN message object with the modified configuration
         * ==========================================================================================
         */
        IfxMultican_Can_MsgObj_initConfig(&g_candebug.canMsgObjConfig, &g_candebug.canSrcNode);

        g_candebug.canMsgObjConfig.msgObjId = SRC_MESSAGE_OBJECT_RX_ID;
        g_candebug.canMsgObjConfig.messageId = CAN_MESSAGE_RXD_ID01;
        g_candebug.canMsgObjConfig.frame = IfxMultican_Frame_receive;
        g_candebug.canMsgObjConfig.rxInterrupt.enabled = TRUE;
        g_candebug.canMsgObjConfig.control.extendedFrame=TRUE;
        g_candebug.canMsgObjConfig.rxInterrupt.srcId = RX_INTERRUPT_SRC_ID;

        g_candebug.canMsgObjConfig.acceptanceMask = 0x0UL;

        IfxMultican_Can_MsgObj_init(&g_candebug.canSrcMsgObjRx, &g_candebug.canMsgObjConfig);
    }
#endif

#if(CAN_PINMAP_TC275LITE_KIT_CAN==1)
    {
        /* ==========================================================================================
         * Destination CAN node configuration and initialization:
         * ==========================================================================================
         *  - load default CAN node configuration into configuration structure
         *
         *  - set destination CAN node in the "Loop-Back" mode (no external pins will be used)
         *  - assign destination CAN node to CAN node 1
         *
         *  - initialize the destination CAN node with the modified configuration
         * ==========================================================================================
         */
        IfxMultican_Can_Node_initConfig(&g_candebug.canNodeConfig, &g_candebug.can);
#if(CAN_LOOPBACK_MODE)
        g_candebug.canNodeConfig.loopBackMode = TRUE;
#endif
        g_candebug.canNodeConfig.nodeId = IfxMultican_NodeId_0;
        g_candebug.canNodeConfig.rxPin  = &IfxMultican_RXD0B_P20_7_IN;
        g_candebug.canNodeConfig.txPin  = &IfxMultican_TXD0_P20_8_OUT;

        IfxMultican_Can_Node_init(&g_candebug.canDstNode, &g_candebug.canNodeConfig);
        /* ==========================================================================================
         * Dst message object configuration and initialization:
         * ==========================================================================================
         *  - load default CAN message object configuration into configuration structure
         *
         *  - define the message object ID
         *  - define the CAN message ID used during arbitration phase
         *  - define the message object as a transmit message object
         *  - enable interrupt generation in case of CAN message transmission
         *  - define interrupt node pointer to be used
         *
         *  - initialize the source CAN message object with the modified configuration
         * ==========================================================================================
         */

           IfxMultican_Can_MsgObj_initConfig(&g_candebug.canMsgObjConfig, &g_candebug.canDstNode);

           g_candebug.canMsgObjConfig.msgObjId = DST_MESSAGE_OBJECT_TX_ID;
           g_candebug.canMsgObjConfig.messageId = CAN_MESSAGE_TXD_ID01;
           g_candebug.canMsgObjConfig.frame = IfxMultican_Frame_transmit;
           g_candebug.canMsgObjConfig.txInterrupt.enabled = TRUE;
           g_candebug.canMsgObjConfig.control.extendedFrame = TRUE;
           g_candebug.canMsgObjConfig.txInterrupt.srcId = TX_INTERRUPT_SRC_ID;

           IfxMultican_Can_MsgObj_init(&g_candebug.canDstMsgObjTx, &g_candebug.canMsgObjConfig);

           IfxMultican_Can_MsgObj_initConfig(&g_candebug.canMsgObjConfig, &g_candebug.canDstNode);

           g_candebug.canMsgObjConfig.msgObjId = DST_MESSAGE_OBJECT_RX_ID;
           g_candebug.canMsgObjConfig.messageId = CAN_MESSAGE_RXD_ID01;
           g_candebug.canMsgObjConfig.frame = IfxMultican_Frame_receive;
           g_candebug.canMsgObjConfig.rxInterrupt.enabled = TRUE;
           g_candebug.canMsgObjConfig.control.extendedFrame = TRUE;
           g_candebug.canMsgObjConfig.rxInterrupt.srcId = RX_INTERRUPT_SRC_ID;

          IfxMultican_Can_MsgObj_init(&g_candebug.canDstMsgObjRx, &g_candebug.canMsgObjConfig);


          //set EN mode and low
          IfxPort_setPinMode(&MODULE_P20, 6,  IfxPort_Mode_outputPushPullGeneral);
          IfxPort_setPinLow(&MODULE_P20, 6);

    }
#endif
}

/* Function to initialize both TX and RX messages with the default data values.
 * After initialization of the messages, the TX message will be transmitted.
 */
#define TRANSMIT_TEST     0
#define TRANSMIT_DEBUG    1
#define TRANSMIT_MODE    (TRANSMIT_DEBUG)
IFX_EXTERN sint16 g_TotalCountAcircle;

void transmitCanDebugMessage(void)
{
    /* Define the content of the data to be transmitted */
    static IfxMultican_Status  sendStatus = IfxMultican_Status_ok;
    static uint32 dataLow,dataHigh;
    static uint32 can_tx_id;
    static uint32 tx_seq =0;
#if(TRANSMIT_MODE==TRANSMIT_TEST)
    dataLow  = 0xD0C01000;
    dataHigh = 0xBA876543;

    dataLow = dataLow +1;
    if(dataLow >= 0xFFFFFFFF)
    {
        dataHigh=dataHigh+1;
    }
#elif(TRANSMIT_MODE==TRANSMIT_DEBUG)
    IFX_EXTERN uint32 count_A,count_Z;
    IFX_EXTERN sint16 cycleTotalCount;
    IFX_EXTERN sint16 Encoder_RawPosition;
//    IFX_EXTERN sint16 spiEndcoderPos;
    IFX_EXTERN uint32 g_TimerCtrlStep;

    IFX_EXTERN uint16 g_Duty_ADC;
    IFX_EXTERN uint16 u8DrvDuty;

    IFX_EXTERN uint8 g_PosCtrlStep;
    IFX_EXTERN sint16 show_commuPoint;
    IFX_EXTERN sint16 Encoder_StartPosition;
    IFX_EXTERN uint16 g_absMotSpeed;
    IFX_EXTERN uint16 u8DrvDuty_Speed;
    IFX_EXTERN uint16 REF_Speed;
    IFX_EXTERN uint16 REF_Current;

    IFX_EXTERN uint16 g_DutyLimitMax;
    IFX_EXTERN uint32 g_DutyStarup;
    IFX_EXTERN uint16 u16StartUpCount;
    IFX_EXTERN uint8 g_DriverBoardTemp;
    IFX_EXTERN uint16 BC_current_AD;
    IFX_EXTERN uint8 REF_Torque;
    IFX_EXTERN sint32 error_position;
    IFX_EXTERN uint16 REF_Angle_Position;
    IFX_EXTERN uint16 Actual_Angle_Position;
    IFX_EXTERN uint8 MotorTorque;
    IFX_EXTERN uint8  REF_Current_By_Torque;
    IFX_EXTERN uint32 Zero_Offset_CCW_Read;


#define CANFrame_2ByteVariable_In4Bytes(A,B)  (((uint32)A&0x0000FFFF)+(((uint32)(B)<<16)&0xFFFF0000))
#define CANFrame0_3Bytes(B0,B1,B2,B3) (((uint32)B0&0x000000FF)+(((uint32)(B1)<<8)&0x0000FF00)+(((uint32)(B2)<<16)&0x00FF0000)+(((uint32)(B3)<<24)&0xFF000000))
#define CANFrame4_7Bytes(B4,B5,B6,B7) (((uint32)B4&0x000000FF)+(((uint32)(B5)<<8)&0x0000FF00)+(((uint32)(B6)<<16)&0x00FF0000)+(((uint32)(B7)<<24)&0xFF000000))

   switch(tx_seq)
   {
       case 0x00:
       {
          dataLow  = CANFrame_2ByteVariable_In4Bytes(g_absMotSpeed,Encoder_StartPosition);
          dataHigh = CANFrame4_7Bytes(((uint8)(g_bldc.state)|((uint8)(g_bldc.rot_dir)<<4)),
                                        REF_Torque,
                                        test_data_invalid,
                                      (uint8)(g_bldc.u32DiagCode));//MotorTorque
          can_tx_id = CAN_MESSAGE_TXD_ID00;

          tx_seq++;
       }
       break;
       case 0x01:
       {
          dataLow  = CANFrame_2ByteVariable_In4Bytes(g_TotalCountAcircle,
                                           Encoder_RawPosition);
          dataHigh = CANFrame4_7Bytes(g_DriverBoardTemp,
                                      u8DrvDuty/10,
                                      g_PosCtrlStep,
                                      g_bldc.Voltage_BUS);
          can_tx_id = CAN_MESSAGE_TXD_ID01;

          tx_seq++;
       }
       break;
       case 0x02:
       {
                dataLow  = CANFrame_2ByteVariable_In4Bytes(g_bldc.CurrentU_BUS,
                        g_bldc.CurrentV_BUS );
                dataHigh = CANFrame_2ByteVariable_In4Bytes(g_bldc.CurrentW_BUS,
                        u8DrvDuty_Speed );
                can_tx_id = CAN_MESSAGE_TXD_ID02;

                tx_seq++;
       }
       break;
       case 0x03:
          {
                   dataLow  = CANFrame_2ByteVariable_In4Bytes(g_DutyLimitMax,
                           REF_Speed);
                   dataHigh = CANFrame_2ByteVariable_In4Bytes(g_DutyStarup,
                           REF_Current);//REF_Current
                   can_tx_id = CAN_MESSAGE_TXD_ID03;

                   tx_seq++;
          }
          break;
       case 0x04:
            {
               dataLow  = CANFrame4_7Bytes((uint8)Step_Offset_CW_Read,(uint8)Step_Offset_CCW_Read,
                       (uint8)Zero_Offset_CW_Read,(uint8)Zero_Offset_CCW_Read);
               dataHigh = CANFrame_2ByteVariable_In4Bytes(REF_Angle_Position,Actual_Angle_Position);
               can_tx_id = CAN_MESSAGE_TXD_ID04;

               tx_seq =0x00;
            }
            break;
       default:
       {
          tx_seq = 0x00;
       }
       break;
   }

#else
#endif

   // if( IfxMultican_Status_notSentBusy != sendStatus)
    {
#if(CAN_PINMAP_MDA48VBLDC_CAN0)
    /* Invalidation of the RX message */
   IfxMultican_Message_init(&g_candebug.rxSrcMsg,
                             CAN_MESSAGE_RXD_ID02,
                             INVALID_DATA_VALUE,
                             INVALID_DATA_VALUE,
                             IfxMultican_DataLengthCode_8);

    /* Initialization of the TX message */
    IfxMultican_Message_init(&g_candebug.txSrcMsg,
                             can_tx_id,
                             dataLow,
                             dataHigh,
                             IfxMultican_DataLengthCode_8);

    sendStatus=IfxMultican_Can_MsgObj_sendMessage(&g_candebug.canSrcMsgObjTx, &g_candebug.txSrcMsg);
#endif

#if(CAN_PINMAP_TC275LITE_KIT_CAN)
    IfxMultican_Message_init(&g_candebug.rxDstMsg,
                              CAN_MESSAGE_RXD_ID01 ,
                                 INVALID_DATA_VALUE,
                                 INVALID_DATA_VALUE,
                                 IfxMultican_DataLengthCode_8);

        /* Initialization of the TX message */
        IfxMultican_Message_init(&g_candebug.txDstMsg,
                                 can_tx_id,
                                 dataLow,
                                 dataHigh,
                                 IfxMultican_DataLengthCode_8);

        sendStatus=IfxMultican_Can_MsgObj_sendMessage(&g_candebug.canDstMsgObjTx, &g_candebug.txDstMsg);

#endif
    }

}

#endif
