/**********************************************************************************************************************
 * \file ADC_Queued_Scan.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
*/


#include <TempDetect.h>
#include "ADC.h"
#include "CommutationControl.h"
#include "IfxStm.h"
#include "DutyLimit.h"

uint16 g_Duty_ADC;
float V_Duty;
uint8 g_DriverBoardTemp;
uint16 g_Speed_ADC;
float V_Speed;
float MotorPlate_temp;
#define NTC_ADC_MAX        200
const uint16 ADC_NTC[NTC_ADC_MAX] =
{
  3042, 3006, 2968, 2931, 2893, 2855, 2816, 2777, 2737, 2697, 2657, 2617, 2576, 2536, 2495, 2454, 2413, 2372, 2331, 2290,
  2249, 2209, 2168, 2128, 2087, 2048, 2008, 1968, 1929, 1891, 1852, 1814, 1777, 1740, 1703, 1667, 1631, 1596, 1561, 1527,
  1493, 1460, 1427, 1395, 1364, 1333, 1302, 1273, 1243, 1215, 1186, 1159, 1132, 1105, 1079, 1054, 1029, 1005, 981,  958,
  935,  913,  891,  870,  849,  829,  809,  790,  771,  753,  735,  717,  700,  684,  667,  652,  636,  621,  606,  592,
  578,  565,  551,  538,  526,  514,  502,  490,  479,  468,  457,  446,  436,  426,  416,  407,  398,  389,  380,  371,
  363,  355,  347,  339,  332,  324,  317,  310,  304,  297,  290,  284,  278,  272,  266,  261,  255,  250,  244,  239,
  234,  229,  225,  220,  215,  211,  207,  202,  198,  194,  190,  187,  183,  179,  176,  172,  169,  166,  162,  159,
  156,  153,  150,  147,  144,  142,  139,  136,  134,  131,  129,  126,  124,  122,  120,  117,  115,  113,  111,  109,
  107,  105,  103,  102,  100,  98,   96,   95,   93,   91,   90,   88,   87,   85,   84,   82,   81,   80,   78,   77,
  76,   75,   73,   72,   71,   70,   69,   68,   67,   65,   64,   63,   62,   61,   60,   60,   59,   58,   57,   56,

};//3042


void DutyInput_ADC(void)
{


   float V_tracker1 = 5.0;
   float V_Duty_MAX = V_tracker1*0.9;

   V_Duty = ADC_result[2][1]*Factor_DAC;
   if (K_VOL_DUTY_ADC_MIN<=V_Duty&&V_Duty<=K_VOL_DUTY_ADC_MAX)
   {
       g_Duty_ADC = (uint8)(85*V_Duty/V_Duty_MAX);
   }
   else if(V_Duty<K_VOL_DUTY_ADC_MIN)
   {
       g_Duty_ADC = K_MOTOR_DRVPWM_DUTY_MIN;
   }
   else
   {
       g_Duty_ADC = g_DutyLimitMax;
   }
   //g_Duty_ADC=V_Speed*10;

}

void SpeedInput_ADC(void)
{

//    float V_Speed_MAX = 4.5;  //unit:V
    uint16 Speed_ADC;
    V_Speed = ADC_result[2][1]*Factor_DAC;
    if (K_VOL_Speed_ADC_MIN<=V_Speed&&V_Speed<=K_VOL_Speed_ADC_MAX)
    {
        Speed_ADC = (uint16)(1030*V_Speed-1135);
        g_Speed_ADC = ((int)(Speed_ADC/100))*100;
    }
    else if(V_Speed<K_VOL_Speed_ADC_MIN)
    {
        g_Speed_ADC = 100;
    }
    else
    {
        g_Speed_ADC = 3500;
    }
}

void MotorPlateTemp_Detect(void)
{

        uint32 temp_val=0;

        for(uint8 t=0;t<10;t++)
        {
            temp_val+=ADC_result[3][5];
//            uint32 ticks = IfxStm_getTicksFromMilliseconds(&MODULE_STM0, 5);
//            IfxStm_waitTicks(&MODULE_STM0, ticks);
        }


        for(uint8 i=0;i<NTC_ADC_MAX;i++)
        {
            if(temp_val/10 >= ADC_NTC[i])
             {
                g_DriverBoardTemp = i;
                break;
             }
         }
}

